export const trades = [
    {
        username : "simah",
        give: "Sweatshirt",
        recieve: "Nike Sweatpants",
        time: "1/30/2023 9:00 PM",
        loc: "Quad",
    },
    {
        username : "mwang",
        give: "Asus Zephyrus G15",
        recieve: "Ipad (2021)",
        time: "1/31/2023 10:00 PM",
        loc: "Commons Dining Hall",
    },
    {
        username : "mwang",
        give: "Nvidia 2070ti",
        recieve: "Nintendo Switch",
        time: "2/14/2023 10:00 AM",
        loc: "Dunn Hall",
    },
    {
        username : "simah",
        give: "Vintage Tommy Hoodie",
        recieve: "Cargo Pants",
        time: "2/12/2023 1:00 PM",
        loc: "Aspire College Station",
    },
    {
        username : "ssloan",
        give: "Polaroid Camera",
        recieve: "Nintendo Wii",
        time: "1/29/2023 10:00 PM",
        loc: "Quad",
    },
    {
        username : "shreakar",
        give: "Purple Rain Shirt",
        recieve: "Oversized Sweater",
        time: "1/29/2023 2:30 PM",
        loc: "MSC Gates Ballroom",
    },
    {
        username : "ssloan",
        give: "Chipotle Duffel",
        recieve: "Walmart Hoodie",
        time: "1/30/2023 10:00 PM",
        loc: "Quad",
    },
    {
        username : "ssloan",
        give: "Polaroid Camera",
        recieve: "Nintendo Wii",
        time: "1/31/2023 10:00 PM",
        loc: "Quad",
    },
    {
        username : "shreakar",
        give: "Purple Rain Shirt",
        recieve: "Oversized T-shirt",
        time: "1/29/2023 2:30 PM",
        loc: "MSC Gates Ballroom",
    },
    {
        username : "shreakar",
        give: "Purple Rain Shirt",
        recieve: "Cargo Pants",
        time: "1/29/2023 2:30 PM",
        loc: "MSC Gates Ballroom",
    },
    
]